public class LawFirm
{
    public static void main(String[] args)
    {
	Client client1 = new Client();
	Client client2 = new Client();
	Client client3 = new Client();
	Client client4 = new Client();
	Client client5 = new Client();
	Attorney attorney1 = new Attorney();
	Attorney attorney2 = new Attorney();
	client1.setClientNumber(1);
	client1.setID(1);
	client1.setFirstName("Howard");
	client1.setLastName("Stern");
	client1.setBalance(120.05);
	client2.setClientNumber(2);
	client2.setID(2);
	client2.setFirstName("Robert");
	client2.setLastName("Frost");
	client2.setBalance(70.25);
	client3.setClientNumber(3);
	client3.setID(1);
	client3.setFirstName("Tony");
	client3.setLastName("Stark");
	client3.setBalance(225.50);
	client4.setClientNumber(4);
	client4.setID(2);
	client4.setFirstName("Alex");
	client4.setLastName("Turner");
	client4.setBalance(20.22);
	client5.setClientNumber(5);
	client5.setID(1);
	client5.setFirstName("Blake");
	client5.setLastName("Griffin");
	client5.setBalance(125.00);
	attorney1.setID(1);
	attorney1.setFirstName("Phoenix");
	attorney1.setLastName("Wright");
	attorney1.setSalary(100000.00);
	attorney1.setID(2);
	attorney2.setFirstName("Don");
	attorney2.setLastName("Mitchell");
	attorney2.setSalary(250000);
	System.out.println();
	System.out.println("Client 1 Info:");
	System.out.println("Client Number: " + client1.getClientNumber());
	System.out.println("Client's Attorney ID: " + client1.getID());
	System.out.println("Client's Name: " + client1.getFirstName() + " " + client1.getLastName());
	System.out.println("Client's Balance: $" + client1.getBalance());
	System.out.println("");
	System.out.println("Client 2 Info:");
	System.out.println("Client Number: " + client2.getClientNumber());
	System.out.println("Client's Attorney ID: " + client2.getID());
	System.out.println("Client's Name: " + client2.getFirstName() + " " + client2.getLastName());
	System.out.println("Client's Balance: $" + client2.getBalance());
	System.out.println("");
	System.out.println("Client 3 Info:");
	System.out.println("Client Number: " + client3.getClientNumber());
	System.out.println("Client's Attorney ID: " + client3.getID());
	System.out.println("Client's Name: " + client3.getFirstName() + " " + client3.getLastName());
	System.out.println("Client's Balance: $" + client3.getBalance());
	System.out.println("");
	System.out.println("Client 4 Info:");
	System.out.println("Client Number: " + client4.getClientNumber());
	System.out.println("Client's Attorney ID: " + client4.getID());
	System.out.println("Client's Name: " + client4.getFirstName() + " " + client4.getLastName());
	System.out.println("Client's Balance: $" + client4.getBalance());
	System.out.println("");
	System.out.println("Client 5 Info:");
	System.out.println("Client Number: " + client5.getClientNumber());
	System.out.println("Client's Attorney ID: " + client5.getID());
	System.out.println("Client's Name: " + client5.getFirstName() + " " + client5.getLastName());
	System.out.println("Client's Balance: $" + client5.getBalance());
	System.out.println();
	System.out.println("Attorney Information:");
	System.out.println("Attorney 1 Info:");
	System.out.println("Attorney 1 ID: " + attorney1.getID());
	System.out.println("Attorney 1's Name: " + attorney1.getFirstName() + " " + attorney1.getLastName());
	System.out.println("Attorney 1's Salary: $" + attorney1.getSalary());
	System.out.println();
	System.out.println("Attorney 2 Info:");
	System.out.println("Attorney 2 ID: " + attorney2.getID());
	System.out.println("Attorney 2's Name: " + attorney2.getFirstName() + " " + attorney2.getLastName());
	System.out.println("Attorney 2's Salary: $" + attorney2.getSalary());
	System.out.println();
    }
}
	